server:
  port: 7100
spring:
  application:
    name: 07-ms-cfg-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RoroLi/git-cloud-config.git
          username: git-username
          password: git-password
